template = "{{date}}{{{local-mail}}} | {{{volume}}} | {{{wifi}}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local-mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{{#if contents}} | <fc=#FF0>!</fc>{{/if}}"

[ blocks.volume ]
kind = "pulse-volume"
template = """
<action=`pactl set-sink-mute \"{{sink_name}}\" toggle` button=2>\
<action=`pactl set-sink-volume \"{{sink_name}}\" -5%` button=1>\
<action=`pactl set-sink-volume \"{{sink_name}}\" +5%` button=3>\
<action=`pactl set-sink-volume \"{{sink_name}}\" -1%` button=5>\
<action=`pactl set-sink-volume \"{{sink_name}}\" +1%` button=4>\
{{~#if muted~}}
    <fc=#F00>
{{~else~}}{{~#if (lte volume 35)~}}
    <fc=#555>
{{~else~}}{{~#if (gt volume 100)~}}
    <fc=#FF0>
{{~else~}}
    <fc=#FFF>
{{~/if~}}{{~/if~}}{{~/if~}}
{{volume}}</fc>%\
</action></action></action></action></action>\
"""

[ blocks.wifi ]
kind = "network"
device = "wlan0"
template = """
{{~#if (eq operstate "up")~}}
    <fc=#FFF>{{essid}}</fc>
{{~else~}}
    <fc=#F00>network down</fc>
{{~/if~}}
"""
