template = "{{date}}{{local_mail}} | {{weather}} | CPU: {{cpu}} | Mem: {{memory}} | Vol: {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local_mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{% if contents %} | ^fg(#FF0)!^fg() {% endif %}"

[ blocks.weather ]
kind = "interval"
command = "curl"
args = [
    "-s",
    "https://forecast.weather.gov/MapClick.php?FcstType=json&lat=47.8608&lon=-123.9370"
    ]
interval = 1800
json = true
template = """\
{%- set weather = output.currentobservation.Weather -%}
{%- if weather != "NA" -%}{{weather}} {%- endif -%}
{%- set temp = output.currentobservation.Temp | int -%}
{%- if temp < 55 -%}
    ^fg(#00F)
{%- elif temp > 80 -%}
    ^fg(#F00)
{%- else -%}
    ^fg(#FFF)
{%- endif -%}
{{temp}}°^fg()\
"""

[ blocks.cpu ]
kind = "cpu"
template = """
{%- if cpu_times.non_idle < 20 -%}
    ^fg(#FFF)
{%- elif cpu_times.non_idle > 50 -%}
    ^fg(#F00)
{%- else -%}
    ^fg(#00F)
{%- endif -%}
{{cpu_times.non_idle | round(precision=1)}}%^fg()\
"""
interval = 5

[ blocks.memory ]
kind = "interval"
command = "awk"
args = [
    "/MemTotal:/{total=$2}/MemAvailable:/{avail=$2}END{printf \"%.01f\", 100 * (1 - avail/total)}",
    "/proc/meminfo",
    ]
interval = 30
template = """
{%- if output | int > 80 -%}
    ^fg(#F00)
{%- else -%}
    ^fg(#FFF)
{%- endif -%}
{{output}}^fg()%\
"""

[ blocks.volume ]
kind = "pulse-volume"
template = """
^ca(1, pactl set-sink-volume {{sink_name}} -5%)\
^ca(2, pactl set-sink-mute {{sink_name}} toggle)\
^ca(3, pactl set-sink-volume {{sink_name}} +5%)\
^ca(4, pactl set-sink-volume {{sink_name}} +1%)\
^ca(5, pactl set-sink-volume {{sink_name}} -1%)\
{%- if muted -%}
    ^fg(#F00)
{%- elif volume <= 35 -%}
    ^fg(#555)
{%- elif volume > 100 -%}
    ^fg(#FF0)
{%- else -%}
    ^fg(#FFF)
{%- endif -%}
{{volume}}%\
^fg()^ca()^ca()^ca()^ca()^ca()\
"""

[ blocks.wifi ]
kind = "network"
device = "wlo1"
template = """
{%- if operstate == "up" -%}
    ^fg(#FFF){{essid}}^fg()
{%- else -%}
    ^fg(#F00){{device}} {{operstate}}^fg()
{%- endif -%}
"""
