template = "{{date}}{{local_mail}} | {{weather}} | CPU: {{cpu}} | Mem: {{memory}} | Vol: {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local_mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{% if contents %} | <fc=#FF0>!</fc>{% endif %}"

[ blocks.weather ]
kind = "interval"
command = "curl"
args = [
    "-s",
    "https://forecast.weather.gov/MapClick.php?FcstType=json&lat=47.8608&lon=-123.9370"
    ]
interval = 1800
json = true
template = """\
{%- set temp = output.currentobservation.Temp | int -%}
{%- if temp < 55 -%}
    {%- set color="#00F" -%}
{%- elif temp > 80 -%}
    {%- set color="#F00" -%}
{%- else -%}
    {%- set color="#FF" -%}
{%- endif -%}
{%- set weather = output.currentobservation.Weather -%}
{%- if weather != "NA" -%}{{weather}} {%- endif -%}<fc={{color}}>{{temp}}°</fc>\
"""

[ blocks.cpu ]
kind = "cpu"
template = """
{%- if cpu_times.non_idle < 20 -%}
    {%- set color="#FFF" -%}
{%- elif cpu_times.non_idle > 50 -%}
    {%- set color="#F00" -%}
{%- else -%}
    {%- set color="#00F" -%}
{%- endif -%}
<fc={{color}}>{{cpu_times.non_idle | round(precision=1)}}%</fc>\
"""
interval = 5

[ blocks.memory ]
kind = "interval"
command = "awk"
args = [
    "/MemTotal:/{total=$2}/MemAvailable:/{avail=$2}END{printf \"%.01f\", 100 * (1 - avail/total)}",
    "/proc/meminfo",
    ]
interval = 30
template = """
{%- if output | int > 80 -%}{% set color="#F00" %}{% else %}{% set color="#FFF" %}{% endif -%}
<fc={{color}}>{{output}}%</fc>\
"""

[ blocks.volume ]
kind = "pulse-volume"
template = """\
{%- if muted -%}
    {%- set color="#F00" -%}
{%- elif volume <= 35 -%}
    {%- set color="#555" -%}
{%- elif volume > 100 -%}
    {%- set color="#FF0" -%}
{%- else -%}
    {%- set color="#FFF" -%}
{%- endif -%}
<action=`pactl set-sink-mute "{{sink_name}}" toggle` button=2>\
<action=`pactl set-sink-volume "{{sink_name}}" -5%` button=1>\
<action=`pactl set-sink-volume "{{sink_name}}" +5%` button=3>\
<action=`pactl set-sink-volume "{{sink_name}}" -1%` button=5>\
<action=`pactl set-sink-volume "{{sink_name}}" +1%` button=4>\
<fc={{color}}>{{volume}}%</fc>\
</action></action></action></action></action>\
"""

[ blocks.wifi ]
kind = "network"
device = "wlo1"
template = """
{%- if operstate == "up" -%}
    <fc=#FFF>{{essid}}</fc>
{%- else -%}
    <fc=#F00>{{device}} {{operstate}}</fc>
{%- endif -%}
"""
