template = "{{date}}{{local_mail}} | Mem: {{memory}} | Vol: {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local_mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{% if contents %} | <fc=#FF0>!</fc>{% endif %}"

[ blocks.memory ]
kind = "interval"
command = "awk"
args = [
    "/MemTotal:/{total=$2}/MemFree:/{free=$2}END{printf \"%.0f\", 100*free/total}",
    "/proc/meminfo",
    ]
interval = 30
template = """
{%- if output | int > 80 -%}
    <fc=#F00>
{%- else -%}
    <fc=#FFF>
{%- endif -%}
{{output}}%</fc>\
"""

[ blocks.volume ]
kind = "pulse-volume"
template = """\
<action=`pactl set-sink-mute "{{sink_name}}" toggle` button=2>\
<action=`pactl set-sink-volume "{{sink_name}}" -5%` button=1>\
<action=`pactl set-sink-volume "{{sink_name}}" +5%` button=3>\
<action=`pactl set-sink-volume "{{sink_name}}" -1%` button=5>\
<action=`pactl set-sink-volume "{{sink_name}}" +1%` button=4>\
{%- if muted -%}
    <fc=#F00>
{%- elif volume <= 35 -%}
    <fc=#555>
{%- elif volume > 100 -%}
    <fc=#FF0>
{%- else -%}
    <fc=#FFF>
{%- endif -%}
{{volume}}%</fc>\
</action></action></action></action></action>\
"""

[ blocks.wifi ]
kind = "network"
device = "wlo1"
template = """
{%- if operstate == "up" -%}
    <fc=#FFF>{{essid}}</fc>
{%- else -%}
    <fc=#F00>{{device}} {{operstate}}</fc>
{%- endif -%}
"""
