template = "{{date}}{{local_mail}} | {{weather}} | CPU: {{cpu}} | Mem: {{memory}} | Vol: {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local_mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{% if contents %} | %{F#FF0}!%{F-}{% endif %}"

[ blocks.weather ]
kind = "interval"
command = "curl"
args = [
    "-s",
    "https://forecast.weather.gov/MapClick.php?FcstType=json&lat=47.8608&lon=-123.9370"
    ]
interval = 1800
json = true
template = """\
{%- set weather = output.currentobservation.Weather -%}
{%- if weather != "NA" -%}{{weather}} {%- endif -%}
{%- set temp = output.currentobservation.Temp | int -%}
{%- if temp < 55 -%}
    %{F#00F}
{%- elif temp > 80 -%}
    %{F#F00}
{%- else -%}
    %{F#FFF}
{%- endif -%}
{{temp}}°%{F-}\
"""

[ blocks.cpu ]
kind = "cpu"
template = """
{%- if cpu_times.non_idle < 20 -%}
    %{F#FFF}
{%- elif cpu_times.non_idle > 50 -%}
    %{F#F00}
{%- else -%}
    %{F#00F}
{%- endif -%}
{{cpu_times.non_idle | round(precision=1)}}%%%{F-}\
"""
interval = 5

[ blocks.memory ]
kind = "interval"
command = "awk"
args = [
    "/MemTotal:/{total=$2}/MemAvailable:/{avail=$2}END{printf \"%.01f\", 100 * (1 - avail/total)}",
    "/proc/meminfo",
    ]
interval = 30
template = """
{%- if output | int > 80 -%}
    %{F#F00}
{%- else -%}
    %{F#FFF}
{%- endif -%}
{{output}}%%%{F-}\
"""

[ blocks.volume ]
kind = "pulse-volume"
template = """
%{A:pactl set-sink-volume {{sink_name}} -5%:}\
%{A2:pactl set-sink-mute {{sink_name}} toggle:}\
%{A3:pactl set-sink-volume {{sink_name}} +5%:}\
%{A4:pactl set-sink-volume {{sink_name}} +1%:}\
%{A5:pactl set-sink-volume {{sink_name}} -1%:}\
{%- if muted -%}
    %{F#F00}
{%- elif volume <= 35 -%}
    %{F#555}
{%- elif volume > 100 -%}
    %{F#FF0}
{%- else -%}
    %{F#FFF}
{%- endif -%}
{{volume}}%%\
%{F-}%{A}%{A}%{A}%{A}%{A}\
"""

[ blocks.wifi ]
kind = "network"
device = "wlo1"
template = """
{%- if operstate == "up" -%}
    %{F#FFF}{{essid}}%{F-}
{%- else -%}
    %{F#F00}{{device}} {{operstate}}%{F-}
{%- endif -%}
"""
