template = "{{date}}{{local-mail}} | {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local-mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{{#if contents}} | %{F#FF0}!%{F-}{{/if}}"

[ blocks.volume ]
kind = "pulse-volume"
template = """
{{~#if muted~}}
    %{F#F00}
{{~else~}}{{~#if (lte volume 35)~}}
    %{F#555}
{{~else~}}{{~#if (gt volume 100)~}}
    %{F#FF0}
{{~else~}}
    %{F#FFF}
{{~/if~}}{{~/if~}}{{~/if~}}
%{A:pactl set-sink-volume {{sink_name}} -5%:}\
%{A2:pactl set-sink-mute {{sink_name}} toggle:}\
%{A3:pactl set-sink-volume {{sink_name}} +5%:}\
%{A4:pactl set-sink-volume {{sink_name}} +1%:}\
%{A5:pactl set-sink-volume {{sink_name}} -1%:}\
{{volume}}%%\
%{A}%{A}%{A}%{A}%{A}%{F-}\
"""

[ blocks.wifi ]
kind = "network"
device = "wlan0"
template = """
{{~#if (eq operstate "up")~}}
    %{F#FFF}{{essid}}%{F-}
{{~else~}}
    %{F#F00}network down%{F-}
{{~/if~}}
"""
