template = "{{date}}{{local-mail}} | {{volume}} | {{wifi}}"

[ blocks.date ]
kind = "interval"
command = "date"
args = ['+%a %b %d %R']
interval = 60

[ blocks.local-mail ]
kind = "inotify"
file = "/var/mail/username"
template = "{{#if contents}} | ^fg(#FF0)!^fg(){{/if}}"

[ blocks.volume ]
kind = "pulse-volume"
template = """
{{~#if muted~}}
    ^fg(#F00)
{{~else~}}{{~#if (lte volume 35)~}}
    ^fg(#555)
{{~else~}}{{~#if (gt volume 100)~}}
    ^fg(#FF0)
{{~else~}}
    ^fg(#FFF)
{{~/if~}}{{~/if~}}{{~/if~}}
^ca(1, pactl set-sink-volume {{sink_name}} -5%)\
^ca(2, pactl set-sink-mute {{sink_name}} toggle)\
^ca(3, pactl set-sink-volume {{sink_name}} +5%)\
^ca(4, pactl set-sink-volume {{sink_name}} +1%)\
^ca(5, pactl set-sink-volume {{sink_name}} -1%)\
{{volume}}%\
^ca()^ca()^ca()^ca()^ca()^fg()\
"""

[ blocks.wifi ]
kind = "network"
device = "wlan0"
template = """
{{~#if (eq operstate "up")~}}
    ^fg(#FFF){{essid}}^fg()
{{~else~}}
    ^fg(#F00)network down^fg()
{{~/if~}}
"""
